# Generated by Django 3.2.20 on 2023-09-21 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Srk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliment', models.CharField(max_length=100)),
                ('rel_user_1_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srk_rel_user_1_1', to=settings.AUTH_USER_MODEL)),
                ('rel_user_n_n', models.ManyToManyField(blank=True, related_name='srk_rel_user_n_n', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
